
name: DropinCI
on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run Chown on wait for it
        run: chmod +x ./webservice/wait-for-it.sh
      # Runs a set of commands using the runners shell
      - name: build and Run docker-compose
        run: docker-compose up --build 
      - name: 'Test the GET response'
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:3000/hello'
          responseCode: '200,500'
          timeout: 2000
          interval: 500
        
