
name: DropinCI
on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run chmod for Webservice
        run: chmod +x ./webservice/wait-for-it.sh
      - name: Run chmod for Personservice
        run: chmod +x ./personservice/wait-for-it.sh
      - name: run docker compose with build flag
        run: docker-compose up --build 
      - name: 'Test the GET response'
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'webservice:3000/hello'
          responseCode: '200'
          timeout: 500
          interval: 100
        
